package com.mobile.scraper
import android.app.*;import android.graphics.Color;import android.os.Bundle;import android.view.*;import android.webkit.*;import android.widget.*;import org.json.JSONObject;import java.net.URLEncoder;import java.util.*
data class T(val id:Int,var title:String="New Tab",var url:String="https://www.google.com",var web:WebView?=null,val net:MutableList<String> = mutableListOf())
class MainActivity:Activity(){
 lateinit var root:LinearLayout;lateinit var tabsRow:LinearLayout;lateinit var page:FrameLayout;lateinit var bar:EditText;lateinit var insp:LinearLayout;lateinit var out:TextView
 val ts=mutableListOf<T>();val closed=ArrayDeque<T>();var a=0;var id=0;var ih=300;var section="HOME";var zoom=100
 fun dp(n:Int)= (n*resources.displayMetrics.density).toInt();fun cur()=ts.getOrNull(a)
 fun B(s:String)=Button(this).apply{text=s;textSize=10f;isAllCaps=false;setTextColor(Color.WHITE);setPadding(2,0,2,0)}
 override fun onCreate(b:Bundle?){super.onCreate(b);ui();new("https://www.google.com")}
 fun ui(){root=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setBackgroundColor(Color.rgb(22,22,22))};tabsRow=LinearLayout(this);root.addView(HorizontalScrollView(this).apply{addView(tabsRow)},LinearLayout.LayoutParams(-1,dp(42)))
  val n=LinearLayout(this);val bk=B("‹");val fw=B("›");val re=B("↻");val hm=B("⌂");val mm=B("⋮");bar=EditText(this).apply{hint="Search or enter address";setSingleLine();setTextColor(Color.WHITE);setHintTextColor(Color.GRAY);textSize=12f};listOf(bk,fw,re,hm).forEach{n.addView(it,LinearLayout.LayoutParams(dp(38),dp(44)))};n.addView(bar,LinearLayout.LayoutParams(0,dp(44),1f));n.addView(mm,LinearLayout.LayoutParams(dp(42),dp(44)));root.addView(n)
  page=FrameLayout(this);root.addView(page,LinearLayout.LayoutParams(-1,0,1f));insp=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setBackgroundColor(Color.rgb(30,30,30))};val h=LinearLayout(this);val grip=TextView(this).apply{text="☰ Inspector — drag";setTextColor(Color.LTGRAY);setOnTouchListener(R())};val sz=B("Size");val cl=B("Clear");val co=B("⌄");h.addView(grip,LinearLayout.LayoutParams(0,dp(40),1f));h.addView(sz,LinearLayout.LayoutParams(dp(55),dp(40)));h.addView(cl,LinearLayout.LayoutParams(dp(55),dp(40)));h.addView(co,LinearLayout.LayoutParams(dp(45),dp(40)));insp.addView(h)
  val names=listOf("HOME","ELEMENTS","NETWORK","CONSOLE","STORAGE","PRODUCTS","PAGES","EXPORT");val r=LinearLayout(this);names.forEach{x->val q=B(x);q.setOnClickListener{section=x;show()};r.addView(q,LinearLayout.LayoutParams(dp(82),dp(38)))};insp.addView(HorizontalScrollView(this).apply{addView(r)});out=TextView(this).apply{setTextColor(Color.LTGRAY);textSize=10f;setTextIsSelectable(true);setPadding(8,8,8,8)};insp.addView(ScrollView(this).apply{addView(out)},LinearLayout.LayoutParams(-1,0,1f));root.addView(insp,LinearLayout.LayoutParams(-1,dp(ih)))
  bk.setOnClickListener{cur()?.web?.let{if(it.canGoBack())it.goBack()}};fw.setOnClickListener{cur()?.web?.let{if(it.canGoForward())it.goForward()}};re.setOnClickListener{cur()?.web?.reload()};hm.setOnClickListener{load("https://www.google.com")};mm.setOnClickListener{menu(mm)};bar.setOnEditorActionListener{_,_,_->load(bar.text.toString());true};sz.setOnClickListener{sizes()};cl.setOnClickListener{cur()?.net?.clear();show()};co.setOnClickListener{setH(if(ih>60)50 else 300)};setContentView(root)}
 fun new(u:String,privateMode:Boolean=false){val t=T(++id);ts.add(t);a=ts.lastIndex;make(t,privateMode);tabs();load(u)}
 fun make(t:T,pv:Boolean){val w=WebView(this);w.settings.javaScriptEnabled=true;w.settings.domStorageEnabled=true;w.settings.setSupportZoom(true);w.settings.builtInZoomControls=true;w.settings.displayZoomControls=false;if(pv)w.settings.cacheMode=WebSettings.LOAD_NO_CACHE;w.addJavascriptInterface(X(t),"MobileScraper");w.webChromeClient=object:WebChromeClient(){override fun onConsoleMessage(c:ConsoleMessage):Boolean{t.net.add("CONSOLE ${c.message()}");if(cur()?.id==t.id)show();return true}};w.webViewClient=object:WebViewClient(){override fun shouldInterceptRequest(v:WebView,r:WebResourceRequest):WebResourceResponse?{t.net.add("${r.method} ${r.url}");return null};override fun onPageStarted(v:WebView?,u:String?,f:android.graphics.Bitmap?){t.url=u?:t.url;runOnUiThread{bar.setText(t.url);tabs()}};override fun onPageFinished(v:WebView?,u:String?){t.url=u?:t.url;t.title=v?.title?.ifBlank{"Page"}?:"Page";runOnUiThread{bar.setText(t.url);tabs()};hook(t)}};t.web=w}
 fun hook(t:T){t.web?.evaluateJavascript("""(function(){if(window.__S3)return;window.__S3=1;function p(k,o){try{MobileScraper.post(k,JSON.stringify(o))}catch(e){}};var f=fetch;if(f)window.fetch=function(i,o){var u=typeof i==='string'?i:i.url||'';p('r',{u:u,m:o&&o.method||'GET'});return f.apply(this,arguments)};})();""",null)}
 inner class X(val t:T){@JavascriptInterface fun post(k:String,d:String){runOnUiThread{try{val o=JSONObject(d);t.net.add("${o.optString("m")} ${o.optString("u")}");show()}catch(_:Exception){}}}}
 fun tabs(){tabsRow.removeAllViews();ts.forEachIndexed{i,t->{val q=B((if(i==a)"● " else "")+t.title.take(12)+" ×");q.setOnClickListener{switch(i)};q.setOnLongClickListener{tabMenu(i,q);true};tabsRow.addView(q,LinearLayout.LayoutParams(dp(145),dp(42)))};val p=B("+");p.setOnClickListener{new("https://www.google.com")};tabsRow.addView(p,LinearLayout.LayoutParams(dp(48),dp(42)))}
 fun switch(i:Int){if(i !in ts.indices)return;a=i;page.removeAllViews();cur()?.web?.let{page.addView(it,FrameLayout.LayoutParams(-1,-1))};bar.setText(cur()?.url?:"");show()}
 fun tabMenu(i:Int,v:View){val p=PopupMenu(this,v);listOf("New tab","Duplicate","Close","Reopen closed").forEach{p.menu.add(it)};p.setOnMenuItemClickListener{when(it.title.toString()){"New tab"->new("https://www.google.com");"Duplicate"->new(ts[i].url);"Close"->close(i);"Reopen closed"->if(closed.isNotEmpty())new(closed.removeFirst().url)};true};p.show()}
 fun close(i:Int){closed.addFirst(ts.removeAt(i));closed.first.web?.destroy();if(ts.isEmpty())new("https://www.google.com")else{a=minOf(a,ts.lastIndex);switch(a)}}
 fun menu(v:View){val p=PopupMenu(this,v);listOf("New tab","New private tab","Duplicate current tab","Desktop site","Find in page","Zoom","Settings","History").forEach{p.menu.add(it)};p.setOnMenuItemClickListener{when(it.title.toString()){"New tab"->new("https://www.google.com");"New private tab"->new("https://www.google.com",true);"Duplicate current tab"->cur()?.let{new(it.url)};"Desktop site"->desktop();"Find in page"->find();"Zoom"->sizes();"Settings"->settings();"History"->history()};true};p.show()}
 fun desktop(){cur()?.let{it.web?.settings?.userAgentString="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 Chrome/151 Safari/537.36";it.web?.reload()}}
 fun find(){val e=EditText(this);AlertDialog.Builder(this).setTitle("Find in page").setView(e).setPositiveButton("Find"){_,_->cur()?.web?.findAllAsync(e.text.toString())}.setNegativeButton("Close",null).show()}
 fun sizes(){val x=arrayOf("75%","90%","100%","110%","125%","150%","175%","200%");AlertDialog.Builder(this).setTitle("Page zoom").setItems(x){_,i->zoom=x[i].dropLast(1).toInt();cur()?.web?.settings?.textZoom=zoom}.show()}
 fun setH(x:Int){ih=maxOf(dp(50),minOf(dp(700),x));insp.layoutParams=LinearLayout.LayoutParams(-1,ih);insp.requestLayout()};inner class R:View.OnTouchListener{var sy=0f;var sh=0;override fun onTouch(v:View,e:MotionEvent):Boolean{if(e.action==0){sy=e.rawY;sh=ih};if(e.action==2)setH(sh+(sy-e.rawY).toInt());return true}}
 fun settings(){val box=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL};val js=CheckBox(this).apply{text="JavaScript";isChecked=true};val im=CheckBox(this).apply{text="Load images";isChecked=true};box.addView(js);box.addView(im);AlertDialog.Builder(this).setTitle("Browser Settings").setView(box).setPositiveButton("Apply"){_,_->cur()?.web?.settings?.javaScriptEnabled=js.isChecked;cur()?.web?.settings?.loadsImagesAutomatically=im.isChecked}.setNeutralButton("Clear site data"){_,_->CookieManager.getInstance().removeAllCookies(null);cur()?.web?.clearCache(true)}.setNegativeButton("Close",null).show()}
 fun history(){AlertDialog.Builder(this).setTitle("History").setMessage(ts.joinToString("\n\n"){it.title+"\n"+it.url}).setPositiveButton("OK",null).show()}
 fun show(){val t=cur()?:return;when(section){"HOME"->out.text="SCRAPING BROWSER V3\n\nTabs: ${ts.size}\nURL: ${t.url}\nNetwork: ${t.net.size}\n\nDrag inspector to resize.";"NETWORK"->out.text=t.net.takeLast(300).reversed().joinToString("\n\n");"CONSOLE"->out.text=t.net.filter{it.startsWith("CONSOLE")}.reversed().joinToString("\n\n");"ELEMENTS"->js(t,"JSON.stringify({title:document.title,url:location.href,links:[...document.links].slice(0,100).map(x=>({text:x.innerText,href:x.href})),forms:[...document.forms].map(x=>({action:x.action,method:x.method}))})"){out.text="DOM\n$it\n\nSelectors: [data-product-id], [itemtype*=Product], [class*=product]"};"PRODUCTS"->js(t,"JSON.stringify([...document.querySelectorAll('[data-product-id],[itemtype*=Product],[class*=product]')].slice(0,100).map(e=>({text:e.innerText,id:e.getAttribute('data-product-id'),class:e.className,html:e.outerHTML.slice(0,1500)})))"){out.text="PRODUCTS\n$it"};"PAGES"->js(t,"JSON.stringify({next:[...document.querySelectorAll('a,button')].filter(e=>/next|load more/i.test(e.innerText||'')).map(e=>({text:e.innerText,href:e.href})),links:[...document.links].map(e=>e.href).filter(x=>/page=|offset=|cursor=/.test(x))})"){out.text="PAGES\n$it"};"STORAGE"->{val c=CookieManager.getInstance().getCookie(t.url)?:"none";js(t,"JSON.stringify({local:Object.fromEntries(Object.keys(localStorage).map(k=>[k,localStorage.getItem(k)])),session:Object.fromEntries(Object.keys(sessionStorage).map(k=>[k,sessionStorage.getItem(k)]))})"){out.text="COOKIES\n$c\nSTORAGE\n$it"}};"EXPORT"->out.text="PYTHON\nimport requests\n# use captured NETWORK request\n\nCURL\ncurl -X GET <captured-url>\n\nJS FETCH\nfetch('<captured-url>')"}}
 fun js(t:T,c:String,d:(String)->Unit){t.web?.evaluateJavascript(c){d(it?:"")}}
 fun load(s:String){var u=s.trim();if(u.isEmpty())return;if(!u.startsWith("http://")&&!u.startsWith("https://"))u="https://www.google.com/search?q="+URLEncoder.encode(u,"UTF-8");cur()?.let{it.url=u;it.web?.loadUrl(u)}}
 override fun onBackPressed(){cur()?.web?.let{if(it.canGoBack()){it.goBack();return}};super.onBackPressed()}
}
